# Generated by Django 2.2 on 2019-09-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdflist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='image',
        ),
    ]
